# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Bumper.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Bumper.proto',
  package='gamePlayer',
  syntax='proto2',
  serialized_pb=_b('\n\x0c\x42umper.proto\x12\ngamePlayer\"L\n\x06\x42umper\x12%\n\x04side\x18\x01 \x02(\x0e\x32\x17.gamePlayer.Bumper.Side\"\x1b\n\x04Side\x12\x08\n\x04LEFT\x10\x00\x12\t\n\x05RIGHT\x10\x01')
)



_BUMPER_SIDE = _descriptor.EnumDescriptor(
  name='Side',
  full_name='gamePlayer.Bumper.Side',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='LEFT', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RIGHT', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=77,
  serialized_end=104,
)
_sym_db.RegisterEnumDescriptor(_BUMPER_SIDE)


_BUMPER = _descriptor.Descriptor(
  name='Bumper',
  full_name='gamePlayer.Bumper',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='side', full_name='gamePlayer.Bumper.side', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _BUMPER_SIDE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=104,
)

_BUMPER.fields_by_name['side'].enum_type = _BUMPER_SIDE
_BUMPER_SIDE.containing_type = _BUMPER
DESCRIPTOR.message_types_by_name['Bumper'] = _BUMPER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Bumper = _reflection.GeneratedProtocolMessageType('Bumper', (_message.Message,), dict(
  DESCRIPTOR = _BUMPER,
  __module__ = 'Bumper_pb2'
  # @@protoc_insertion_point(class_scope:gamePlayer.Bumper)
  ))
_sym_db.RegisterMessage(Bumper)


# @@protoc_insertion_point(module_scope)
