# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: encoderControl.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='encoderControl.proto',
  package='gamePlayer',
  syntax='proto2',
  serialized_pb=_b('\n\x14\x65ncoderControl.proto\x12\ngamePlayer\"f\n\x0e\x45ncoderControl\x12\x33\n\x07\x63ommand\x18\x01 \x02(\x0e\x32\".gamePlayer.EncoderControl.Command\"\x1f\n\x07\x43ommand\x12\t\n\x05\x42\x45GIN\x10\x00\x12\t\n\x05RESET\x10\x01')
)



_ENCODERCONTROL_COMMAND = _descriptor.EnumDescriptor(
  name='Command',
  full_name='gamePlayer.EncoderControl.Command',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='BEGIN', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RESET', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=107,
  serialized_end=138,
)
_sym_db.RegisterEnumDescriptor(_ENCODERCONTROL_COMMAND)


_ENCODERCONTROL = _descriptor.Descriptor(
  name='EncoderControl',
  full_name='gamePlayer.EncoderControl',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='command', full_name='gamePlayer.EncoderControl.command', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ENCODERCONTROL_COMMAND,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=138,
)

_ENCODERCONTROL.fields_by_name['command'].enum_type = _ENCODERCONTROL_COMMAND
_ENCODERCONTROL_COMMAND.containing_type = _ENCODERCONTROL
DESCRIPTOR.message_types_by_name['EncoderControl'] = _ENCODERCONTROL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EncoderControl = _reflection.GeneratedProtocolMessageType('EncoderControl', (_message.Message,), dict(
  DESCRIPTOR = _ENCODERCONTROL,
  __module__ = 'encoderControl_pb2'
  # @@protoc_insertion_point(class_scope:gamePlayer.EncoderControl)
  ))
_sym_db.RegisterMessage(EncoderControl)


# @@protoc_insertion_point(module_scope)
