# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ultrasonicArray.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ultrasonicArray.proto',
  package='gamePlayer',
  syntax='proto2',
  serialized_pb=_b('\n\x15ultrasonicArray.proto\x12\ngamePlayer\"w\n\x0fUltrasonicArray\x12\x14\n\x0c\x66ront_center\x18\x01 \x02(\x02\x12\x12\n\nfront_left\x18\x02 \x02(\x02\x12\x13\n\x0b\x66ront_right\x18\x03 \x02(\x02\x12\x11\n\trear_left\x18\x04 \x02(\x02\x12\x12\n\nrear_right\x18\x05 \x02(\x02')
)




_ULTRASONICARRAY = _descriptor.Descriptor(
  name='UltrasonicArray',
  full_name='gamePlayer.UltrasonicArray',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='front_center', full_name='gamePlayer.UltrasonicArray.front_center', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='front_left', full_name='gamePlayer.UltrasonicArray.front_left', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='front_right', full_name='gamePlayer.UltrasonicArray.front_right', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rear_left', full_name='gamePlayer.UltrasonicArray.rear_left', index=3,
      number=4, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rear_right', full_name='gamePlayer.UltrasonicArray.rear_right', index=4,
      number=5, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=156,
)

DESCRIPTOR.message_types_by_name['UltrasonicArray'] = _ULTRASONICARRAY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UltrasonicArray = _reflection.GeneratedProtocolMessageType('UltrasonicArray', (_message.Message,), dict(
  DESCRIPTOR = _ULTRASONICARRAY,
  __module__ = 'ultrasonicArray_pb2'
  # @@protoc_insertion_point(class_scope:gamePlayer.UltrasonicArray)
  ))
_sym_db.RegisterMessage(UltrasonicArray)


# @@protoc_insertion_point(module_scope)
